name: Reusable • Build & Deploy to GoDaddy (FTP/FTPS)

on:
  workflow_call:
    inputs:
      server_dir:
        required: true
        type: string
        description: "Path relative to FTP root (e.g., ./ or ./subfolder/)"
      node_version:
        required: false
        type: string
        default: "20"
      build_cmd:
        required: false
        type: string
        default: "npm ci && npm run build"
      local_dir:
        required: false
        type: string
        default: "dist/"
      protocol:
        required: false
        type: string
        default: "ftps"   # ftps|ftp
      clean_slate:
        required: false
        type: boolean
        default: true
      log_level:
        required: false
        type: string
        default: "minimal"  # minimal|standard|verbose
    secrets:
      FTP_HOST:
        required: true
      FTP_USER:
        required: true
      FTP_PASS:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: "npm"

      - name: Build
        run: ${{ inputs.build_cmd }}

      # optional marker to verify deployments (you can keep or remove)
      - name: Write deploy marker
        run: echo "deployed $GITHUB_SHA at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > ${{ inputs.local_dir }}/__deploy-check.txt

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          protocol: ${{ inputs.protocol }}
          local-dir: ${{ inputs.local_dir }}
          server-dir: ${{ inputs.server_dir }}
          dangerous-clean-slate: ${{ inputs.clean_slate }}
          log-level: ${{ inputs.log_level }}